INSERT INTO Teams (TeamID, TName, City) VALUES (001, 'Diamondbacks', 'Arizona');
INSERT INTO Teams (TeamID, TName, City) VALUES (002, 'Athletics', 'Las Vegas');
INSERT INTO Teams (TeamID, TName, City) VALUES (003, 'Braves', 'Atlanta');
INSERT INTO Teams (TeamID, TName, City) VALUES (004, 'Orioles', 'Baltimore');
INSERT INTO Teams (TeamID, TName, City) VALUES (005, 'Red Sox', 'Boston');
INSERT INTO Teams (TeamID, TName, City) VALUES (006, 'Cubs', 'Chicago');
INSERT INTO Teams (TeamID, TName, City) VALUES (007, 'White Sox', 'Chicago');
INSERT INTO Teams (TeamID, TName, City) VALUES (008, 'Reds', 'Cincinatti');
INSERT INTO Teams (TeamID, TName, City) VALUES (009, 'Guardians', 'Cleveland');
INSERT INTO Teams (TeamID, TName, City) VALUES (010, 'Rockies', 'Colorado');
INSERT INTO Teams (TeamID, TName, City) VALUES (011, 'Tigers', 'Detroit');
INSERT INTO Teams (TeamID, TName, City) VALUES (012, 'Astros', 'Houston');
INSERT INTO Teams (TeamID, TName, City) VALUES (013, 'Royals', 'Kansas City');
INSERT INTO Teams (TeamID, TName, City) VALUES (014, 'Angels', 'Los Angeles');
INSERT INTO Teams (TeamID, TName, City) VALUES (015, 'Dodgers', 'Los Angeles');
INSERT INTO Teams (TeamID, TName, City) VALUES (016, 'Marlins', 'Miami');
INSERT INTO Teams (TeamID, TName, City) VALUES (017, 'Brewers', 'Milwaukee');
INSERT INTO Teams (TeamID, TName, City) VALUES (018, 'Twins', 'Minnesota');
INSERT INTO Teams (TeamID, TName, City) VALUES (019, 'Mets', 'New York');
INSERT INTO Teams (TeamID, TName, City) VALUES (020, 'Yankees', 'New York');
INSERT INTO Teams (TeamID, TName, City) VALUES (021, 'Phillies', 'Philadelphia');
INSERT INTO Teams (TeamID, TName, City) VALUES (022, 'Pirates', 'Pittsburgh');
INSERT INTO Teams (TeamID, TName, City) VALUES (023, 'Padres', 'San Diego');
INSERT INTO Teams (TeamID, TName, City) VALUES (024, 'Giants', 'San Fransisco');
INSERT INTO Teams (TeamID, TName, City) VALUES (025, 'Mariners', 'Seattle');
INSERT INTO Teams (TeamID, TName, City) VALUES (026, 'Cardinals', 'St. Louis');
INSERT INTO Teams (TeamID, TName, City) VALUES (027, 'Rays', 'Tampa Bay');
INSERT INTO Teams (TeamID, TName, City) VALUES (028, 'Rangers', 'Texas');
INSERT INTO Teams (TeamID, TName, City) VALUES (029, 'Blue Jays', 'Toronto');
INSERT INTO Teams (TeamID, TName, City) VALUES (030, 'Nationals', 'Washington');

INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (101, 'Ketel', 'Marte', 'Second Base', TO_DATE('1993-10-12', 'YYYY-MM-DD'), 001);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (102, 'Soderstrom', 'Tyler', 'First Base', TO_DATE('2001-11-24', 'YYYY-MM-DD'), 002);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (103, 'Austin', 'Riley', 'Third Base', TO_DATE('1997-04-02', 'YYYY-MM-DD'), 003);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (104, 'Adley', 'Rutschman', 'Catcher', TO_DATE('1998-02-06', 'YYYY-MM-DD'), 004);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (105, 'Wilyer', 'Abreu', 'Right Field', TO_DATE('1999-06-24', 'YYYY-MM-DD'), 005);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (106, 'Kyle', 'Tucker', 'Right Field', TO_DATE('1997-01-17', 'YYYY-MM-DD'), 006);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (107, 'Luis', 'Robert Jr.', 'Center Field', TO_DATE('1997-08-03', 'YYYY-MM-DD'), 007);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (108, 'Elly', 'De La Cruz', 'Shortstop', TO_DATE('2002-01-11', 'YYYY-MM-DD'), 008);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (109, 'Jose', 'Ramirez', 'Third Base', TO_DATE('1992-09-17', 'YYYY-MM-DD'), 009);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (110, 'Kris', 'Bryant', 'Designated Hitter', TO_DATE('1992-01-04', 'YYYY-MM-DD'), 010);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (111, 'Spencer', 'Torkelson', 'First Base', TO_DATE('1999-08-26', 'YYYY-MM-DD'), 011);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (112, 'Jose', 'Altuve', 'Left Field', TO_DATE('1990-05-06', 'YYYY-MM-DD'), 012);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (113, 'Bobby', 'Wiit Jr.', 'Shortstop', TO_DATE('2000-06-14', 'YYYY-MM-DD'), 013);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (114, 'Yoan', 'Moncada', 'Third Base', TO_DATE('1995-05-27', 'YYYY-MM-DD'), 014);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (115, 'Mookie', 'Betts', 'Second Base', TO_DATE('1992-10-07', 'YYYY-MM-DD'), 015);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (116, 'Kyle', 'Stowers', 'Right Field', TO_DATE('1998-01-02', 'YYYY-MM-DD'), 016);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (117, 'Christian', 'Yelich', 'Left Field', TO_DATE('1991-12-05', 'YYYY-MM-DD'), 017);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (118, 'Byron', 'Buxon', 'Center Field', TO_DATE('1993-12-18', 'YYYY-MM-DD'), 018);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (119, 'Pete', 'Alonso', 'First Base', TO_DATE('1994-12-07', 'YYYY-MM-DD'), 019);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (120, 'Aaron', 'Judge', 'Right Field', TO_DATE('1992-04-26', 'YYYY-MM-DD'), 020);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (121, 'Kyle', 'Schwarber', 'Designated Hitter', TO_DATE('1993-03-05', 'YYYY-MM-DD'), 021);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (122, 'Oniel', 'Cruz', 'Center Field', TO_DATE('1998-10-04', 'YYYY-MM-DD'), 022);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (123, 'Manny', 'Machado', 'Third Base', TO_DATE('1992-07-06', 'YYYY-MM-DD'), 023);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (124, 'Jung Hoo', 'Lee', 'Center Field', TO_DATE('1998-08-20', 'YYYY-MM-DD'), 024);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (125, 'Jorge', 'Polanco', 'Designated Hitter', TO_DATE('1993-07-05', 'YYYY-MM-DD'), 025);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (126, 'Nolan', 'Arenado', 'Third Base', TO_DATE('1991-04-16', 'YYYY-MM-DD'), 026);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (127, 'Chandler', 'Simpson', 'Center Field', TO_DATE('2000-11-18', 'YYYY-MM-DD'), 027);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (128, 'Kyle', 'Schwarber', 'Designated Hitter', TO_DATE('1993-03-05', 'YYYY-MM-DD'), 028);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (129, 'Alejandro', 'Kirk', 'Catcher', TO_DATE('1998-11-06', 'YYYY-MM-DD'), 029);
INSERT INTO Players (PlayerID, FName, LName, Position, DOB, TeamID) VALUES (130, 'CJ', 'Abrams', 'Shortstop', TO_DATE('2000-10-03', 'YYYY-MM-DD'), 030);

INSERT INTO Seasons (SeasonID, Year) VALUES (001, 2025);
INSERT INTO Seasons (SeasonID, Year) VALUES (002, 2024);
INSERT INTO Seasons (SeasonID, Year) VALUES (003, 2023);

INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (101, 001, 100, 10, 50, 8);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (101, 002, 90, 12, 34, 11);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (101, 003, 134, 30, 80, 14);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (102, 001, 120, 4, 50, 18);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (102, 002, 190, 13, 34, 13);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (102, 003, 132, 20, 50, 20);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (103, 001, 78, 15, 19, 2);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (103, 002, 150, 17, 40, 6);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (103, 003, 174, 22, 99, 3);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (104, 001, 120, 4, 50, 18);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (104, 002, 190, 13, 34, 13);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (104, 003, 102, 8, 92, 22);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (105, 001, 143, 13, 36, 6);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (105, 002, 142, 21, 63, 7);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (105, 003, 141, 19, 77, 8);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (106, 001, 170, 33, 102, 3);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (106, 002, 142, 29, 60, 3);
INSERT INTO Stats (PlayerID, SeasonID, Hits, Homers, RBIs, Walks) VALUES (106, 003, 141, 10, 88, 5);

